#!/bin/sh
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd ); cd "$SCRIPT_DIR"
ARCHISO_PRESET="$1"
[ -z "$ARCHISO_PRESET" ] && ARCHISO_PRESET=zestiso-core
[ ! -d "$ARCHISO_PRESET" ] && echo "[ERROR] ArchISO preset \"$ARCHISO_PRESET\" not found in $SCRIPT_DIR" && exit

mkdir -p /tmp/archiso-tmp
rm -rf /tmp/archiso-tmp/"$ARCHISO_PRESET"
cp -r "$ARCHISO_PRESET" /tmp/archiso-tmp/"$ARCHISO_PRESET"

if [ -d /tmp/archiso-tmp/"$ARCHISO_PRESET"/depends ]; then
	cd "$ARCHISO_PRESET"/depends
	for DEPEND in $(ls "$ARCHISO_PRESET"/depends); do

	done
fi

















exit
#### OLD CODE ###

## Copy core/baseline preset



## Merge with custom preset
if [ "$ARCHISO_PRESET" != "zestiso-core" ]; then
	cp -rf "$ARCHISO_PRESET/airootfs" /tmp/archiso-tmp/"$ARCHISO_PRESET/" &> /dev/null
	cp -rf "$ARCHISO_PRESET/efiboot" /tmp/archiso-tmp/"$ARCHISO_PRESET/" &> /dev/null
	cp -rf "$ARCHISO_PRESET/grub" /tmp/archiso-tmp/"$ARCHISO_PRESET/" &> /dev/null
	cp -rf "$ARCHISO_PRESET/syslinux" /tmp/archiso-tmp/"$ARCHISO_PRESET/" &> /dev/null
	cp -rf "$ARCHISO_PRESET/pacman.conf" /tmp/archiso-tmp/"$ARCHISO_PRESET/" &> /dev/null
	cp -rf "$ARCHISO_PRESET/profiledef.sh" /tmp/archiso-tmp/"$ARCHISO_PRESET/" &> /dev/null
	(cat "$ARCHISO_PRESET/bootstrap_packages.x86_64" >> /tmp/archiso-tmp/"$ARCHISO_PRESET/bootstrap_packages.x86_64") &> /dev/null
	(cat "$ARCHISO_PRESET/packages.x86_64" >> /tmp/archiso-tmp/"$ARCHISO_PRESET/packages.x86_64") &> /dev/null
fi
